import type { Metadata } from 'next'
import Wrapper from './components/hoc/Wrapper'
import './globals.css'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Wrapper>
            {children}
          </Wrapper>
        </Providers>
      </body>
    </html>
  )
}
